
MOCK_PRODUCTS = [
    {
        "id": "mock_1",
        "safe_id": "mock1",
        "variant_id": "gid://shopify/ProductVariant/123456789",
        "title": "Charizard 1st Ed.",
        "set": "Base Set",
        "rarity": "Ultra Rare",
        "price": 3750000.00,
        "image": "https://lh3.googleusercontent.com/aida-public/AB6AXuBnlxbCCW7ccJLac_9xcLOXxM-MQgVnouqpyKkiCDfy4FfqfF-di-JUgJIqWJ8lCnc_HYiWlsxm5jCjWF56iaORuRVkL_kbOB-RBc9rxKCLj0jPzxQ1ClNuMffzy_F0XUAW8RgtTJUIN8Ec2cIxTKENalMJzzdGbAl9Eq87pK2r5s6Gmo9cNEupS31EY89f5KlNZv6Q2sSYz5mfZH3RN51Tj1fLS6U82OqUoiU5toqg6brAXMD5VihYlGsJCQzBKrRuPvi1aTztNq19",
        "badge": "PSA 10",
        "badge_color": "bg-green-500",
        "card_number": "4/102",
        "card_number": "4/102",
        "status": "Sync",
        "quantity_available": 1
    },
    {
        "id": "mock_2",
        "safe_id": "mock2",
        "variant_id": "gid://shopify/ProductVariant/223456789",
        "title": "Umbreon VMAX",
        "set": "Evolving Skies",
        "rarity": "Epic",
        "price": 127500.00,
        "image": "https://lh3.googleusercontent.com/aida-public/AB6AXuCtdgPgDIX7LKx7CSs13Z2Qo2_nFjcpYUYjbnyxcXmQeV16aCY9JiUPZ7bWeSA8ByFo1Vk3LuXfLWgrs9fwUhd7pdr7UBO7GyGRxiqfbF8PaaY8AtRecafC7rJq4Ow8IidJClQYf07gWq-h5nGd8XQDMvnZ1-SPHhScjX5HS0ofmJloG_ZsTA5PWCV1KiufYF5Hcbr4d2hcAAxjrcOy3YRVZp7EVVBerbATuBtvBT12JlAfSAnBCXNA6li_5nA8fcrnZRI24KzMINMo",
        "badge": "BGS 9.5",
        "badge_color": "bg-green-500",
        "card_number": "215/203",
        "card_number": "215/203",
        "status": "Sync",
        "quantity_available": 1
    },
    {
        "id": "mock_3",
        "safe_id": "mock3",
        "variant_id": "gid://shopify/ProductVariant/323456789",
        "title": "Lugia Holo",
        "set": "Neo Genesis",
        "rarity": "Epic",
        "price": 180000.00,
        "image": "https://lh3.googleusercontent.com/aida-public/AB6AXuBsqrAal1Ef4qIB2ndAfwW4htPLSpTatObyqtodT5e4oQzBvKx5SV0GXj1f-uGXsXpG_I1Z2mbAAz-54HoMn7djckfYOEPxSOrANSzzPw3J2HKVMcbfn_Rbo-49MEBLKDdyeuNJ9OHRLX9ZGh46lOxCsT0oFE7wvNv_6T00D5KRLSgVxo8Q0P0jJd8HtlAum6wQNhbANcc5uhkDowle4ap4HExIUqzLoWfktmS5uw5o5XsVrwpbfjgyoLb1tyxFepPHpCtCSYc_WpQk",
        "badge": "CGC 10",
        "badge_color": "bg-green-500",
        "card_number": "9/111",
        "card_number": "9/111",
        "status": "Sync",
        "quantity_available": 1
    },
    {
        "id": "mock_4",
        "safe_id": "mock4",
        "variant_id": "gid://shopify/ProductVariant/423456789",
        "title": "Mewtwo GX Shiny",
        "set": "Hidden Fates",
        "rarity": "Rare",
        "price": 21750.00,
        "image": "https://lh3.googleusercontent.com/aida-public/AB6AXuCim-GEGejIo3Tr8VhZ_xXxGQtGhHua7pBfNrlDmjQcOGG1lv6zRhuBT2OWfrWy679HVnT5txjvF_B7jjcW3f7LxxaGxhPJtJttGnCD1iserH0G24kim3KN5NzARxNqFG8YOgxnwBH2203GpaiBZ83DddFHGhuJdzzqhzjGQaKV090GfTRXHE1_711OaEp2UFKePqproYqMSaPE3E2cg2S7giUyzWjKxYujpVtJg8UHg11DvWV9KSGo2R64GjnUOUlVsho3WLHuqYzK",
        "badge": "RAW NM",
        "badge_color": "bg-primary",
        "card_number": "SV59",
        "card_number": "SV59",
        "status": "Pending",
        "quantity_available": 1
    },
     {
        "id": "mock_5",
        "safe_id": "mock5",
        "variant_id": "gid://shopify/ProductVariant/523456789",
        "title": "Pikachu Base",
        "set": "Base Set",
        "rarity": "Common",
        "price": 750.00,
        "image": "https://images.saymedia-content.com/.image/t_share/MTc0NDU3NjA0NjY3NzYyNjk0/most-valuable-pikachu-cards.png", 
        "badge": "RAW NM",
        "badge_color": "bg-primary",
        "card_number": "58/102",
        "card_number": "58/102",
        "status": "Sync",
        "quantity_available": 5
    },
     {
        "id": "mock_6",
        "safe_id": "mock6",
        "variant_id": "gid://shopify/ProductVariant/623456789",
        "title": "Squirtle",
        "set": "Base Set",
        "rarity": "Uncommon",
        "price": 1800.00,
        "image": "https://i.ebayimg.com/images/g/T~cAAOSw~h1h6~9~/s-l1600.jpg",
        "badge": "RAW NM",
        "badge_color": "bg-primary",
        "card_number": "63/102",
        "card_number": "63/102",
        "status": "Sync",
        "quantity_available": 3
    }

]
